plugins { id 'com.android.application' }
android {
    namespace 'cn.jhun.sanjiaohu'
    compileSdk 36
    defaultConfig { applicationId 'cn.jhun.sanjiaohu'; minSdk 26; targetSdk 35; versionCode 33; versionName 'y7c_0.2' }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
